"""First

Revision ID: 613bbf4c9c1a
Revises: 
Create Date: 2022-11-24 19:26:04.400315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613bbf4c9c1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
